# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16ae2e0abc88d7943fca0d6e2234d2b497fa0868bc48813887a456bfea971a74c4707eb2df55cc04e6c2d6a8fd0ab36ec24e7fe0e3d6ad12d9bc2efa78869ad9

test:
  secret_key_base: 915f79d636d89034e2d17849552d4121cd9209eaa41c95ab0be070e328500ebc6c7d349899da285725fb43fc79b14d658f0afe52843715e32fa28b6f6f607f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
